[book]
title = "Rust 设计模式"
authors = ["the rust-unofficial authors"]
description = "Rust设计模式、反模式和典例的目录"
language = "zh"
multilingual = false
src = "."

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/poly000/patterns-zh/"
git-repository-icon = "fa-github"

# [output.linkcheck]  # enable the "mdbook-linkcheck" renderer, disabled due to gh-actions
